<a href="https://colab.research.google.com/github/sanskar-decoder/Ml_logistic_Regression/blob/main/logisticregression_implementation(krish_naik).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#important libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.datasets import make_classification

#Generate a dataset

In [ ]:
X,y=make_classification(n_samples=1000, n_features=10,random_state=45)

Train Test Split

In [ ]:
df=pd.DataFrame(X)

In [ ]:
df['output']=y

In [ ]:
df

0         1         2         3         4         5         6  \
0   -0.070784 -0.059060  0.012882  0.943296 -0.199423  0.093872 -0.707834   
1    0.767601  0.841654  0.391930 -1.376757 -1.253017  1.837804 -0.955603   
2    1.080365 -0.720313 -2.017045 -0.098078  1.505538 -0.798613  1.985952   
3   -0.921898 -0.739911  0.744337  0.977411  1.180594 -1.347697  1.053252   
4   -1.175318  0.086262  1.058239  0.783929 -0.442362 -0.194387 -0.944535   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.431395 -0.819926 -0.129352  0.633469  1.460864 -1.594962  1.578664   
996  1.136250  0.003717  1.782873 -0.226934  0.069421  0.113087  0.197907   
997 -0.730791 -1.352997  1.463181  1.632943  2.211209  0.238778  2.067227   
998 -0.091200 -0.000539  1.039922  0.708317 -0.239289  1.027438 -0.646836   
999 -0.678739  0.660792 -1.381356 -1.069827 -0.987519 -1.311885 -0.760396   

            7         8         9  output  
0    0.081261 -0.725350 -1.735946       1  
1    0.479615  0.468981 -0.757992       0  
2   -1.160567  0.422257  0.870514       0  
3   -0.712697 -0.034112  0.022239       1  
4   -1.144389  0.316958  2.081673       1  
..        ...       ...       ...     ...  
995  0.892688  0.184150  0.116034       1  
996 -1.312773  0.267115  1.584811       1  
997  0.271768  0.423154 -1.768918       1  
998  1.075787  0.995646  1.114542       1  
999  1.809068  1.294355 -1.767558       0  

[1000 rows x 11 columns]

In [ ]:
df.head()

0         1         2         3         4         5         6  \
0 -0.070784 -0.059060  0.012882  0.943296 -0.199423  0.093872 -0.707834   
1  0.767601  0.841654  0.391930 -1.376757 -1.253017  1.837804 -0.955603   
2  1.080365 -0.720313 -2.017045 -0.098078  1.505538 -0.798613  1.985952   
3 -0.921898 -0.739911  0.744337  0.977411  1.180594 -1.347697  1.053252   
4 -1.175318  0.086262  1.058239  0.783929 -0.442362 -0.194387 -0.944535   

          7         8         9  output  
0  0.081261 -0.725350 -1.735946       1  
1  0.479615  0.468981 -0.757992       0  
2 -1.160567  0.422257  0.870514       0  
3 -0.712697 -0.034112  0.022239       1  
4 -1.144389  0.316958  2.081673       1

In [ ]:
df.shape

(1000, 11)

#Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=45)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((700, 10), (300, 10), (700,), (300,))

In [ ]:
from sklearn.linear_model import LogisticRegression

reg=LogisticRegression()

In [ ]:
reg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred=reg.predict(X_test)

y_test=Actual output

 y_pred=Predicted Output

Perfomance Metrix

perfomance metrix

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
print('accuracy',accuracy_score(y_test,y_pred))
print()
print(f'Confusion matrix : \n{confusion_matrix(y_test,y_pred)}')
print(classification_report(y_test,y_pred))

accuracy 0.9533333333333334

Confusion matrix : 
[[133   8]
 [  6 153]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       141
           1       0.95      0.96      0.96       159

    accuracy                           0.95       300
   macro avg       0.95      0.95      0.95       300
weighted avg       0.95      0.95      0.95       300



# **Hyperparameter Tunning an cross validation**


In [ ]:
#c_values in inversly porpotional to lambda
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_values=[100,0.1,0.01,1.0,0.001]
solvers=['lbfgs', 'liblinear','newton-cg','newton-cholesky','sag','saga']


In [ ]:
params=dict(penalty=penalty,C=c_values,solver=solvers)

In [ ]:
print(params)

{'penalty': ['l1', 'l2', 'elasticnet'], 'C': [100, 0.1, 0.01, 1.0, 0.001], 'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']}


Stratified K fold for cross Validation
--

In [ ]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

**GridSearch CV**
--

In [ ]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=params,cv=cv,n_jobs=-1)

**Fit Model in Grid**



In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 0.1, 0.01, 1.0, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

Predicted Output
--

In [ ]:
y_prdg1=grid.predict(X_test)

In [ ]:
y_prdg1

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
y_test

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0])

**check for a  parameter what model take**
--


In [ ]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

check for perfomance Metrics
how model work

In [ ]:
print('accuracy',accuracy_score(y_test,y_prdg1))
print()
print(f'Confusion matrix : \n{confusion_matrix(y_test,y_prdg1)}')
print(classification_report(y_test,y_prdg1))

accuracy 0.9633333333333334

Confusion matrix : 
[[136   5]
 [  6 153]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       141
           1       0.97      0.96      0.97       159

    accuracy                           0.96       300
   macro avg       0.96      0.96      0.96       300
weighted avg       0.96      0.96      0.96       300



after applying gridsearch hyperparameter tunning  
--
Accuracy of model=96%

RandomizedSearch CV

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
random=RandomizedSearchCV(estimator=model,param_distributions=params,cv=cv,n_jobs=-1)

**Fit model **
--

In [ ]:
random.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 0.1, 0.01, 1.0, 0.001],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']})

**Predicted Output**
--

In [ ]:
y_prdg2=random.predict(X_test)

In [ ]:
random.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 0.1}

Check for perfomance
--

In [ ]:
print('accuracy',accuracy_score(y_test,y_prdg2))
print()
print(f'Confusion matrix : \n{confusion_matrix(y_test,y_prdg2)}')
print(classification_report(y_test,y_prdg2))

accuracy 0.9633333333333334

Confusion matrix : 
[[135   6]
 [  5 154]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       141
           1       0.96      0.97      0.97       159

    accuracy                           0.96       300
   macro avg       0.96      0.96      0.96       300
weighted avg       0.96      0.96      0.96       300



after applying hyper tunning (Randomized Serach CV)
--
we get
96% accuracy of model
